[package]
name = "rust_ecies"
version = "0.0.1"
authors = ["Mohit Bhasi Thazhath <mohitbt@vt.edu>"]
edition = "2018"

[lib]
name = "rust_ecies"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]

[dependencies]
ecies = "0.2"
base64 = "0.13.0"